### ISSUE TITLE
The first switch is working backwards 

### ISSUE THREAD

**Issue by elishabenabbuyah** [mjsokolo/love-the-args#31]
It gives a translation box when it's "off" and none when it's "on."

**Comment by mjsokolo** [comment]
Yeah this a strange reoccuring bug that I'm having difficulty duplicating. Do remember the exact series of steps that triggered the bug?

**Comment by elishabenabbuyah** [comment]
No, but I'll start again and see if I can replicate it. I'll do it tomorrow.

**Comment by elishabenabbuyah** [comment]
Yeah, weird, I can’t duplicate it either. 

I just want to say how happy playing with this is making me and how every time I go to do something new I think “wow, he thinks of everything.”
