### ISSUE TITLE
Resizing boxes

### ISSUE THREAD

**Issue by elishabenabbuyah** [mjsokolo/love-the-args#46]
Is it possible to make the boxes 
a. manually resizable
b. resize automatically to the height of the text. I'm attaching a screenshot of a problem I just came upon with box sizes as I was marking a mishnah. 
What do you think? Big ask or small?

![image](https://user-images.githubusercontent.com/23532565/129975959-55c23021-57f2-42e1-beb4-623dab6310e9.png)

**Comment by mjsokolo** [comment]
I'm not seeing this error on the most recent version of the sight - can you try refreshing and copy-pasting a large block of text?

**Comment by elishabenabbuyah** [comment]
Tried it on something new and it still leaves a very significant amount of dead space before the next box, both on the right and on the left. 
![image](https://user-images.githubusercontent.com/23532565/130088578-295a0d26-0ade-483b-aa69-26c1507c6407.png)

**Comment by mjsokolo** [comment]
Fixed!
