### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by elishabenabbuyah** [mjsokolo/love-the-args#55]
When I move a box over to the right, it opens the right-click menu. I think I need to show you this one on zoom. I had a hell of a time replicating it, and finally figured out at least one instance, though there may be others.

**Comment by mjsokolo** [comment]
In the process of diagnosing this

**Comment by mjsokolo** [comment]
I pushed up a change which may solve it, but if not, we do a zoom session so you can show me how to duplicate it. Let me know if this is a priority and we can do a quick session today

**Comment by elishabenabbuyah** [comment]
The arrow issue is solved. Thanks so much. The other one is still happening. Try pasting in a text from the daf yomi portal, http://daf-yomi.com/Dafyomi_Page.aspx?vt=2 <http://daf-yomi.com/Dafyomi_Page.aspx?vt=2&massechet=283&amud=3&fs=0> &massechet=283&amud=3&fs=0

Split it at the gemara

Drag the mishnah box over to the right. 

I think that should do it, though that’s not the only condition under which it happens, and it doesn’t happen all the time. 

It does feel like a priority, since the videos keep getting obstructed by it, but I’m booked from 3 until 8. Do you have time at 8?

Thanks Michael.

**Comment by mjsokolo** [comment]
Yep, let's meet at 8, I'll ponder it and see what I can do till then

**Comment by mjsokolo** [comment]
I believe I fixed it now. Context menu was set to trigger after holding right-click for 1000 ms (this is standard behavior for mobile apps). Since this is a desktop application, I undid this default behavior. We can still meet at 8 to confirm that everything is good!
