### ISSUE TITLE
Initial Arrows between boxes need to be shorter 

### ISSUE THREAD

**Issue by elishabenabbuyah** [mjsokolo/love-the-args#56]
Not sure if this is technically a bug, but didn't know how else to label it. 
The initial split is off the bottom of the screen.

**Comment by mjsokolo** [comment]
Not sure I understand this one. I tried the splitting at 100-125% zoom and
the split is on the screen. Can you send a screenshot? Ahhhh.... as I write
this, I think I know what the issue is. OK, interesting. If you can send me
a screenshot to confirm my suspicion, I can fix it today

**Comment by elishabenabbuyah** [comment]
Are you able to replicate the other one? It keeps happening as I’m taping and I can’t seem to avoid it. I can show you on zoom, but I can’t consistently replicate it, which is annoying.

**Comment by mjsokolo** [comment]
by "the other one" do you mean this thread's subject ("the initial arrows
need to be shorter")?

**Comment by mjsokolo** [comment]
The arrow issue should be fixed
