### ISSUE TITLE
pressing enter in the box makes the cursor to to the end of the box

### ISSUE THREAD

**Issue by elishabenabbuyah** [mjsokolo/love-the-args#58]
When I press enter to organize information within a box, for some reason the cursor moves to the end of the box. When the box is really long, this is a problem, as the whole screen needs to be scrolled up each time you press enter.

**Comment by mjsokolo** [comment]
This seems to working fine for me. If I press enter in the box, a new line is added and cursor behaves as expected. I may need to see a demonstration of this, or if you can recreate a small example with text that may help.

**Comment by mjsokolo** [comment]
It looks like it wasn't the cursor that was jumping, but the scrollbar. Fixed, I hope!

**Comment by elishabenabbuyah** [comment]
I do think you are right, though, that it’s the scrollbar. The cursor, unless it’s jumping down and then back up again, seems fixed in its original location.
