### ISSUE TITLE
High Priority - Borders around all boxes (temporary fixes)

### ISSUE THREAD

**Issue by elishabenabbuyah** [mjsokolo/love-the-args#86]
Just a temporary solution until we can get the permanent multi-labelling going...
Currently, we force them to use arrows (which I like) when something will definitely point back. Until we sort out multi-labelling, could we temporarily:
1. Have the arrow option put an automatic border around the box that ONLY pays attention to the FIRST arrow choice (if they use multiple arrows).
2.  Have all options on the list get a box and an arrow option for the meantime (this is less desirable, since it takes away the forced arrow).

**Comment by mjsokolo** [comment]
we're going to do option 1. the first arrow you make adds a box and the label is on the box and the arrow. Any subsequent arrows you add to THAT box, the label is displayed on the arrow.
